In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("C:/Users/Federico/Downloads/Python DS/Día 9/10 - Crea Cualquier Gráfico desde Matplotlib.org/Iluminacion.csv")
df

       Latitud  Longitud  Luminosidad
0     1.764052 -0.202117    49.929240
1     0.400157 -0.833231    98.656690
2     0.978738  1.733600    68.735218
3     2.240893  0.190649    85.794230
4     1.867558 -0.177810    50.499409
...        ...       ...          ...
9995 -1.809282  0.271662    65.661394
9996  0.042359 -0.108997    42.123643
9997  0.516872 -0.057259    18.950191
9998 -0.032921 -1.058931     8.672976
9999  1.298111 -0.326528    14.826581

[10000 rows x 3 columns]